[package]
name = "rust_cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
sha1 = "0.10"
sha2 = "0.10"
md-5 = "0.10"
hex = "0.4"
crossbeam = "0.8"
itertools = "0.10"
rand = "0.8"
sled = "0.34"
